# Generated by Django 3.0.6 on 2020-06-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20200605_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='goal_quantity_num',
            field=models.PositiveIntegerField(default=0, help_text='What is your numeric goal for your daily habit? (ex--50)'),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal_quantity_unit',
            field=models.CharField(default=' ', help_text='What unit of measure are you using for your goal? (ex. pages', max_length=260),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.CharField(help_text='What habit do you want to build?(ex--read)', max_length=260),
        ),
    ]
