# Generated by Django 3.0.6 on 2020-06-09 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_auto_20200609_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
