# Generated by Django 3.0.6 on 2020-06-09 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecord',
            name='quantity',
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='check_mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='quantity_complete',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='recorded_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
